### ISSUE TITLE
Nuxt 2.0 incompatibility

### ISSUE THREAD

**Issue by bovas85** [microcipcip/cookie-universal#18]
Hi, thanks for this.

I'm getting an error on nuxt 2.0 version for this when added into modules:

```
× fatal TypeError: request.charCodeAt is not a function
  at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:408:15)
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:574:20)
  at Nuxt.resolveModule ...
  at process._tickCallback (internal/process/next_tick.js:68:7)
  at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
  at startup (internal/bootstrap/node.js:279:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```

**Comment by microcipcip** [comment]
@bovas85 I've just installed Nuxt 2.0 and I am able to use `this.$cookies` in the mounted() lifecycle without errors. the func `charCodeAt` is not even used in cookie universal, are you sure the error is definitely coming from this package? If it does, I may need more info or a test repo to replicate.
